name: Atualizar Cache de Estatísticas Sísmicas

# Gatilho (continua o mesmo)
on:
  schedule:
    # Corre aos 15 minutos, a cada 2 horas (120 min)
    # (Ex: 00:15, 02:15, 04:15, 06:15, etc.)
    - cron: '15 */2 * * *'
  workflow_dispatch:

# --- V ADICIONA ESTE BLOCO DE CÓDIGO ABAIXO V ---
# Esta é a correção: Dá permissão à Action para fazer "push" (escrever)
# de volta no teu repositório.
permissions:
  contents: write
# --- ^ FIM DA CORREÇÃO ^ ---

jobs:
  build-stats:
    runs-on: ubuntu-latest
    steps:
      
      # O resto do ficheiro permanece exatamente igual
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar Dependências
        run: npm install

      - name: Gerar Ficheiro de Stats
        run: node processar_stats.js

      - name: Commit do Ficheiro JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📊 [Bot] Atualização automática do cache de estatísticas"
          file_pattern: stats_cache.json 
          branch: main # (ou master)
          commit_user_name: StreamNew Stats Bot
          commit_user_email: bot@streamnew.app
          commit_author: StreamNew Stats Bot <streamnew@post.com>
